global:
  scrape_interval:     30s
  evaluation_interval: 30s

scrape_configs:
- job_name: cadvisor
  static_configs:
  - targets:
    - cadvisor:8080

- job_name: prometheus
  static_configs:
  - targets:
    - prometheus:9090

- job_name: node-exporter
  static_configs:
  - targets:
    - node-exporter:9100

- job_name: nginx-exporter
  static_configs:
  - targets:
    - nginx-exporter:9113